function carregar(){
    var msg = window.document.getElementById("msg");
    var img = window.document.getElementById("imagem");
    var data = new Date();
    var hora = data.getHours();

    hora = 19;

    if (hora == 1) {
        msg.innerHTML =  `Agora são: ${hora} hora.`;
        
    } else{

        msg.innerHTML =  `Agora são: ${hora} horas.`;
    }
   


    if (hora >= 0 && hora < 12) {
        img.src = 'manhaCerto.jpg'
        document.body.style.background  =  '#e2cd9f'
    } else if (hora > 12 && hora <= 18){
           img.src = 'tarde.png'
           document.body.style.background = '#ff8c00'
    } else {
        img.src = 'noite.png'
        document.body.style.background = "#241178"

    }
    
}